title: LaHohwa's Workshop
description: "LaHohwa's Workshop - Notes on Recipes and Projects"
baseurl: "/lahohwa_workshop"
url: "https://henryhsi.github.io"
language: en
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag